[package]
name = "autoclown"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xcap = "0.0.10"
imageproc = "0.25.0"
crossterm = "0.27.0"
enigo = "0.2.1"
